### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by psathyrella** [hmorlon/PANDA#12]
So just a suggestion, but given that the docs [linked from cran](https://cran.r-project.org/web/packages/RPANDA/RPANDA.pdf) are mostly just a list of functions (albeit with good descriptions of each function), and thus not super helpful as far as figuring out where to get started (i.e. which functions to run), it might be nice to link [this paper](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12526) from the github readme (and maybe also from the cran docs), since it seems to be a more useful starting place for noobs like me. If there's a better starting place than that paper that I haven't found, that would be great, as well.

For context, I'm coming from [this paper](https://academic.oup.com/sysbio/article/65/3/495/2468938), and am super excited to try out the MGL stuff, thanks for writing it!

**Comment by hmorlon** [comment]
Done in the github readme, thanks for the suggestion! Best Hélène

**Comment by psathyrella** [comment]
woooooooo! thank you!
