### ISSUE TITLE
Fitting environmental model

### ISSUE THREAD

**Issue by alvarezalicia** [hmorlon/PANDA#13]
Dear all,
I am trying to fit an environmental-dependent model using InfTemp data of RPANDA package. My tree goes back to 42.08 Myr at the basal node. And I understand that the InfTemp data goes to 67 Myr. I am sorry about this question (I am a R-user, I do not know anything about programming): Does the fit_env function take this differnce into account or should I indicate something inside the function? I was expecting some relationship between diversification and this variable but I got a result that says that the best model is the one with speciation and extinction as constants (I tried linear and exponential models). So I want to know if I am doing the things right.
Thank you in advance,
Alicia

**Comment by FabienCondamine** [comment]
Dear Alicia,
If your clade age is 42 Myrs old then the fit_env function is working well, and it automatically fit to the temperature data of the clade age. It would have been a problem if the clade age was older than the temperature data (e.g. clade age of 70 Myrs). Am I clear?
Also, you can show me your results for the model selection. Don't hesitate to contact me by email directly. 
Best regards,
Fabien

**Comment by alvarezalicia** [comment]
Dear Fabien
Thank you so much. I sent you an e-mail!

Best regards
Alicia
