### ISSUE TITLE
JSDtree fails on some trees

### ISSUE THREAD

**Issue by richelbilderbeek** [hmorlon/PANDA#23]
When I run `JSDtree`, it usually does exactly what it should: produce a matrix with zeroes on the diagonal and Jensen-Shannon distances in the other cells. Well done :+1:

However, for some trees, the function fails:

```{r}
library(RPANDA)

tree_1 <- ape::read.tree(text = "(t4:0.2969950169,((t1:0.06457926296,t2:0.06457926296):0.0824593208,(t5:0.1346457881,t3:0.1346457881):0.01239279566):0.1499564331);")
tree_2 <- ape::read.tree(text = "((t2:0.07486817339,t5:0.07486817339):0.8541436693,(t1:0.08605484639,(t4:0.06379297152,t3:0.06379297152):0.02226187487):0.8429569963);")
trees <- c(tree_1, tree_2)
jsd <- RPANDA::JSDtree(phylo = trees)[1, 2]

# Should give a number
testthat::expect_false(is.nan(jsd))
```

Running this, gives a warning:

```
Warning messages:
1: In log(x/y) : NaNs produced
2: In log(x/y) : NaNs produced
```

Just for convenience, these are the trees:

![plot](https://user-images.githubusercontent.com/2098230/72731528-321a3b80-3b94-11ea-846e-7fe8263daad0.png)

I would expect either a clear error message or a (valid) result. I hope you will add this reprex to your test suite and fix it.

Just for completness, I add the complete brute-force script I used to find these trees:

```{r}
library(RPANDA)

# reprex
tree_1 <- ape::read.tree(text = "(t4:0.2969950169,((t1:0.06457926296,t2:0.06457926296):0.0824593208,(t5:0.1346457881,t3:0.1346457881):0.01239279566):0.1499564331);")
tree_2 <- ape::read.tree(text = "((t2:0.07486817339,t5:0.07486817339):0.8541436693,(t1:0.08605484639,(t4:0.06379297152,t3:0.06379297152):0.02226187487):0.8429569963);")
trees <- c(tree_1, tree_2)
jsd <- RPANDA::JSDtree(phylo = trees)[1, 2]
testthat::expect_false(is.nan(jsd))

print(ape::write.tree(trees[1]))
print(ape::write.tree(trees[2]))

# Plot
png("~/plot.png")
par(mfrow = c(1,2))
ape::plot.phylo(trees[[1]])
ape::add.scale.bar()
ape::plot.phylo(trees[[2]])
ape::add.scale.bar()
dev.off()

# Brute force search
for (i in seq(1, 100000)) {
  set.seed(i)
  trees <- c(
    ape::rcoal(n = 5),
    ape::rcoal(n = 5)
  )
  jsd <- RPANDA::JSDtree(phylo = trees)[1, 2]
  if (is.nan(jsd)) {
    print(i)
    print(ape::write.tree(trees[1]))
    print(ape::write.tree(trees[2]))
    stop("ERROR")
  }
}
```

Good luck fixing and keep up the good work :+1:

**Comment by elewitus** [comment]
Thanks for your interest.

The kernel density estimates for your first tree include negative numbers, so when these are ln-transformed in the Kullback Liebler divergence metric, it returns NaNs. This should be a straightforward fix that I can push this week. Thanks for drawing my attention to it.

Best,
Eric

**Comment by richelbilderbeek** [comment]
Awesome! Thanks @elewitus :+1:
