### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by dylanHco** [hmorlon/PANDA#36]
Hello:

I am trying to use Clads(), but I am having some difficulties installing RPANDA (any version) on a HPCC and my own computer.

The issue appears to be with "Rmpfr". 
`Warning message in install.packages("Rmpfr"):"installation of package 'Rmpfr' had non-zero exit status" `
`configure: error: Header file mpfr.h not found; maybe use --with-mpfr-include=INCLUDE_PATH`

Does anyone know a way around this? 

Many thanks!
-Dylan

**Comment by JClavel** [comment]
Hi Dylan,

You need the MPFR (and problably gmp) library to be installed on your machines (https://www.mpfr.org/). See the "system requirements" of the Rmpfr package (https://CRAN.R-project.org/package=Rmpfr).
Maybe try to do it through conda?

Regards,

Julien
The GNU MPFR Library<https://www.mpfr.org/>
MPFR Links. Internal links: Latest release: download – documentation – bugs – changes.; Source code: information to use the development repository.; Sample: to ...
www.mpfr.org


________________________________
De : dylanHco <notifications@github.com>
Envoyé : samedi 30 janvier 2021 21:27
À : hmorlon/PANDA <PANDA@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [hmorlon/PANDA] Issues with installation (#36)


Hello:

I am trying to use Clads(), but I am having some difficulties installing RPANDA (any version) on a HPCC and my own computer.

The issue appears to be with "Rmpfr".
Warning message in install.packages("Rmpfr"):"installation of package 'Rmpfr' had non-zero exit status"
configure: error: Header file mpfr.h not found; maybe use --with-mpfr-include=INCLUDE_PATH

Does anyone know a way around this?

Many thanks!
-Dylan
