### ISSUE TITLE
fit_t_standard vs. createModel + fitTipData

### ISSUE THREAD

**Issue by RhettRautsaw** [hmorlon/PANDA#40]
Hi RPANDAs team, 

First off, I just want to say how amazing this package and all the work you do is. But I'm having an issue understanding some of the parameters and differences in the functions. 

Specifically, what is the difference between the `fit_t_standard` function vs. the combination of `createModel` and `fitTipData` functions?

Using the same phylogeny, trait data, and error vector I get different inferred parameters with these two functions. 
When I use the `fitTipData` function with a BM model, the inferred parameters are `m0, v0, d,sigma `. When I use the `fit_t_standard` function the inferred parameters are `sigma2 and nuisance` and there is an additional `theta` parameter. It seems as though `sigma = sigma2`, `v0 = nuisance`, and `m0 = theta`, but what is `d`?

Similarly, for an OU model, `fitTipData` gives `m0, v0, psi, theta, sigma` while `fit_t_standard` gives `sigma2, alpha, nuisance, theta`. It seems like now `theta = theta`, but now I don't know what `m0` or `psi` mean and where is `alpha` in the first function? None of the values in the first function seem to be anywhere near the estimated `alpha` from the second function. 

Am I missing something? Is there a document that explains these parameters in more detail?

Thank you,

Rhett

**Comment by hmorlon** [comment]
Hello Rhett, thank you for your interest in the package. BM in the fitTipData function can include a drift component (BM with drift), d measures this drift. Results of the fitting procedure may depend on how intraspecific variance/measurement error in trait values is dealt with. You can find a document with a detailed tutorial for using the fitTipData function (and explanation of the parameters) in the Online Appendix of the Manceau et al. Syst Bio paper ( https://doi.org/10.1093/sysbio/syw115) available on Dryad (https://datadryad.org/stash/dataset/doi:10.5061/dryad.52636). Unless you want to implement specific models of trait coevolution, i would recommend using our other fit_t functions (eg the fit_t_standard functions, but also potentially others depending on what you want to do), which are more user friendly. Good luck ;)

**Comment by RhettRautsaw** [comment]
Ahhh. I see. Thank you for your quick reply! That is very helpful. :)
