### ISSUE TITLE
HOME: Error in modelTest

### ISSUE THREAD

**Issue by BH-Lab** [hmorlon/PANDA#42]
Dear PANDA team,

Thank you very much for providing such amazing package.

I came across an issue in testing the HOME module incorporated in the package.
When I ran Simulation and Empirical application using the same codes as introduced in HOME Tutorial and showed in Examples of this function, the function sim_microbiota ran normally, but the function HOME_model always ended with an Error:

Error in modelTest(sequences_model, model = c("K80", "F81", "HKY"), G = F, :
Labels in tree and data differ!

I checked the lables in tree file and alignments, they are the same. How could I to address this issue ?

Regards,
Biao

**Comment by BPerezLamarque** [comment]
Dear Biao, 

  Thanks for your feedback. 

First, I would recommend you to run HOME using the HOME package (instead of using HOME through RPANDA, as the HOME package contains the newest functions of HOME).

Then, if the problem persists when using the HOME package, can you send me the script (and the data if any) that you are using for running HOME? The problem seems to come from the function modelTest (from the phangorn R package). 

Thanks!

All the best, 

Benoit

**Comment by BH-Lab** [comment]
Dear Benoit, 

Yes, it is a bug of modelTest within the package of phangorn. I have now fixed it, and HOME works reliably well.

BTW, I am working on virome and would like to figure out the possible host-virome evolution. I have carefully read the paper and tutorial, and it seems that HOME requires microbiota alignments of highly identical sequences. Though lack of counterparts of 16s rRNA, do you think it is reasonable to use viral hallmark genes, such as RdRp, to perform the similiar prediction as bacteriome ? 

Kind regards,

Biao

**Comment by BPerezLamarque** [comment]
Dear Biao, 

Nice to see that you have managed to fix your issue. 

About running HOME on viral sequences, in theory, it should not be a problem, as long as you can get a reliable alignment for your viral sequences (which is an input of HOME). You should just keep in mind that HOME models the DNA evolution of the microbial sequences on the host phylogeny by considering only nucleotide substitutions (and it also tolerates gaps without explicitly modeling the processes of insertion/deletion). Thus, if you suspect that recombinations and/or other processes occurred during the evolution of your viral sequences, they are not currently modeled by HOME, and we don't know how such processes will affect the performances of HOME. In that case, I would recommend only running HOME on individual genes or small gene regions for which you don't expect any recombination to occur. 

Don't hesitate if you have any other questions.

All the best, 

Benoit

**Comment by BH-Lab** [comment]
Great recommendation, many thanks.

Best wishes,

Biao
