### ISSUE TITLE
plot_fit_env(res,InfTemp,tot_time)

### ISSUE THREAD

**Issue by sanjin725** [hmorlon/PANDA#43]
Error in match.fun(FUN) : argument "FUN" is missing, with no default

**Comment by hmorlon** [comment]
Thanks for catching this. I fixed a typo in the code on github, will upload to CRAN in the next release. You can just ignore the error message for now, it does not affect the plots. Thanks!

**Comment by sanjin725** [comment]
Thanks your reply,&nbsp;I also found this error and fixed it. Thank you very much for your program




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月16日(星期五) 下午3:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hmorlon/PANDA] plot_fit_env(res,InfTemp,tot_time) (Issue #43)





 
Thanks for catching this. I fixed a typo in the code on github, will upload to CRAN in the next release. You can just ignore the error message for now, it does not affect the plots. Thanks!
