### ISSUE TITLE
Can you do fit_env models not spanning the entire timespan of the tree?

### ISSUE THREAD

**Issue by jamie-thompson** [hmorlon/PANDA#46]
My environmental data goes to only ~120Mya, but my tree is older than this.  Can I fit these models to a younger age, or do I need to select younger clades?

**Comment by FabienCondamine** [comment]
Hello Jamie,
Thanks for your question. As implemented in RPANDA, the _fit_env_ function requires the environmental variable to cover the entire timeframe of the focal dated tree. If not, the function will return an error message as you may have already seen.
I hope this helps.
Best regards,
