### ISSUE TITLE
error when loading library

### ISSUE THREAD

**Issue by pwkooij** [hmorlon/PANDA#7]
Hi,

I just installed RPANDA on our linux computer, but when I load in the library I receive the following error:

```
Error: package or namespace load failed for 'RPANDA':
objects 'neworder_phylo', 'neworder_pruningwise' are not exported by 'namespace:ape'
```

Then when I try to run `plot(my_tree)` I receive the following error:

```
Error in reorder.phylo(x, order = "postorder") : 
object 'neworder_phylo' not found
```
I made sure I installed all the different packages necessary, but still get this error. Do you think this might have to do with the version of 'ape'?

Cheers
Pepijn

**Comment by JClavel** [comment]
Hi Pepijn,


Thanks for your email.

Can you tell me which version of RPANDA are you using? Is it the CRAN version? I will also needs the version of "ape" and if possible a reproducible example or at least the function you tried to understand what happens.


When loading only ape, have you any errors by running:

library(ape)

tree<-rcoal(5)

tree2<-reorder.phylo(tree, order="postorder")


Cheers,


Julien


________________________________
De : pwkooij <notifications@github.com>
Envoyé : vendredi 28 juillet 2017 13:59
À : hmorlon/PANDA
Cc : Subscribed
Objet : [hmorlon/PANDA] error when loading library (#7)


Hi,

I just installed RPANDA on our linux computer, but when I load in the library I receive the following error:

Error: package or namespace load failed for 'RPANDA':
objects 'neworder_phylo', 'neworder_pruningwise' are not exported by 'namespace:ape'


Then when I try to run plot(my_tree) I receive the following error:

Error in reorder.phylo(x, order = "postorder") :
object 'neworder_phylo' not found


I made sure I installed all the different packages necessary, but still get this error. Do you think this might have to do with the version of 'ape'?

Cheers
Pepijn

**Comment by pwkooij** [comment]
Hi Julien

The version of RPANDA is 1.3, I was forced to reboot my computer and now it seems to be working. I guess it had to do with some of the other packages I had to install first.

Thanks for the quick response though!

Cheers
Pepijn
