### ISSUE TITLE
Error in optim(init, optimLH, method = meth) :  function cannot be evaluated at initial parameters

### ISSUE THREAD

**Issue by Cactusolo** [hmorlon/PANDA#8]
Hi,

I have the code from the RPANDA example, when I ran "fit_env" function with example intial values, it failed with error mentioned above. What's the resolution for this issue?

I also see sombody asked here : https://www.phylobabble.org/t/troubleshooting-rpanda-code/595

I paste my code and data here: https://github.com/Cactusolo/Rpanda_fail_case.
Thanks!

**Comment by hmorlon** [comment]
Hello, 

Yes this a common error as soon as the likelihood cannot be computed with the initial parameters used for the optimisation. Which parameters "fail" depend on the data (i.e. the phylogeny), so there isn't really any other fix than trying with other initial parameter values. One approach to find "reasonable" initial parameter values is to rely on estimates obtained with simpler models. So for example using parameters estimated using fit_bd as initial parameters in fit_env. I hope this helps!

Best

Hélène

**Comment by Cactusolo** [comment]
Thanks for the quick responding! 👍  @hmorlon 

I'll try around with your suggestions and let you know how it goes :)

Miao

**Comment by Cactusolo** [comment]
Hi again,
I have tried all the combinations of parameters estimated by "fit_bd" as initial parameters to feed two specific models using "fit_env", but still failed to find the the optimization. So does this mean "no go" at all ?!
Thanks!
Miao

PS. Two important models **failed**:
_Scenario: lambda is varying as an exponential function of temperature (x)_
_Scenario: lambda varying as an exponential, function of temperature (x) & time (t)_
but _Scenario: lambda varying as an exponential function of time - no temperature dependency_ worked!

**Comment by hmorlon** [comment]
Hello Mia, 

Trying all combinations of parameter values does not really make sense, please only use those that make sense (e.g. lambda estimated from a constant rate birth-death model as the initial parameter value for lambda0 in the environment-dependent model). Something that has to work if the contant rate models run are to use as initial parameter values lambda0 and mu0 estimated from the constant rate models and parameters for the dependency to temperature (alpha, beta) set to 0 (this is then equivalent to the contant rate models). 

Hope this helps

Best

Hélène

**Comment by Cactusolo** [comment]
@hmorlon Thank you so much for your patience! Would you please break down it for me?
saying that I want to test speciation rate is varying exponential, as a function of temperature (x), mu=0, time as t, so:
lambda.x <-function(t,x,y){y[1] * exp(y[2] * x)};
mu.0.t <-function(t,x,y){0} # mu fixed to 0 (no extinction)

par <- list(c(1.541240071, **???**)) _# Based on previous the constant rate birth-death model, the lambda0 was estimated as 1.5412401, then how to set the rate of speciation change (the second par[[1]][2])?_

bvar.x.d0 <- fit_env(tree, InfTemp, tot_time, **f.lamb=lambda.x**, **f.mu=mu.0.t**, **lamb_par=par[[1]][c(1,2)]**, mu_par=c(), fix.mu=TRUE, df=dof, cond="crown", f=fraction, dt=1e-3)

We need another par for lamb_par, beside lambda0 you mentioned in the last post. I tried use the same second par estimated from the other simpler models, doesn't work.

If you are interested in try, my scripts and data are here: https://github.com/Cactusolo/Rpanda_fail_case.

Gratitude!

Miao

**Comment by hmorlon** [comment]
Hello @Cactusolo , i think you may be trying to fit environmental models to phylogenies that are 122 Ma while the temperature data in InfTemp only goes back to 67 Myrs. This is why you get NAs. 
>max(InfTemp$Age)=67.5173

**Comment by Cactusolo** [comment]
Hi @hmorlon , I thought this was the reason initially! However, 1) why t values (68-74) worked? These are all greater than InfTemp$Age; 2) In manual or publications, I didn't see any of the warning of not applying fit_env function to any tree whose max(branching.time) >max(InfTemp$Age), so I though this not the issue.

Anyway, thanks!

Miao
