### ISSUE TITLE
update RPANDA---Error : object 'GIC' is not exported by 'namespace:mvMORPH'

### ISSUE THREAD

**Issue by Cactusolo** [hmorlon/PANDA#9]
installing the source package ‘RPANDA’

trying URL 'https://cran.rstudio.com/src/contrib/RPANDA_1.4.tar.gz'
Content type 'application/x-gzip' length 299199 bytes (292 KB)
downloaded 292 KB

* installing *source* package 'RPANDA' ...
** package 'RPANDA' successfully unpacked and MD5 sums checked
** R
** data
** inst
** byte-compile and prepare package for lazy loading
Error : object 'GIC' is not exported by 'namespace:mvMORPH'
ERROR: lazy loading failed for package 'RPANDA'
* removing 'C:/Users/xxx/R/win-library/3.5/RPANDA'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘RPANDA’ had non-zero exit status

**Comment by JClavel** [comment]
Please try installing with the option 'dependencies=TRUE' or update the last version of 'mvMORPH' on your machine.
`install.packages("RPANDA", dependencies = TRUE)`

Or directly install from gitHub through devtools:
`library(devtools)`
`install_github("hmorlon/PANDA")`

Note that the packages has just been updated and CRAN is still processing the binaries. If you're not using Rtools or a compiler (e.g. 'gfortran') you might need to wait for the binaries to be available on CRAN (in 2-3 days max).

You can check the statut for the binaries online at [https://CRAN.R-project.org/package=RPANDA](https://CRAN.R-project.org/package=RPANDA)

**Comment by Cactusolo** [comment]
@JClavel Thanks for your quick responding! I'll wait for the binaries.

Just let you know that so far the same error generated from both of options you suggested:

**> install.packages("RPANDA", dependencies = TRUE)**
Installing package into ‘C:/Users/XXX/R/win-library/3.5’
(as ‘lib’ is unspecified)
also installing the dependencies ‘praise’, ‘testthat’


  There is a binary version available but the source version is later:
       binary source needs_compilation
RPANDA    1.3    1.4             FALSE

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/praise_1.0.0.zip'
Content type 'application/zip' length 19485 bytes (19 KB)
downloaded 19 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/testthat_2.0.0.zip'
Content type 'application/zip' length 1594906 bytes (1.5 MB)
downloaded 1.5 MB

package ‘praise’ successfully unpacked and MD5 sums checked
package ‘testthat’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\XXX\AppData\Local\Temp\RtmpQhp14r\downloaded_packages
installing the source package ‘RPANDA’

trying URL 'https://cran.rstudio.com/src/contrib/RPANDA_1.4.tar.gz'
Content type 'application/x-gzip' length 299199 bytes (292 KB)
downloaded 292 KB

* installing *source* package 'RPANDA' ...
** package 'RPANDA' successfully unpacked and MD5 sums checked
** R
** data
** inst
** byte-compile and prepare package for lazy loading
Error : object 'GIC' is not exported by 'namespace:mvMORPH'
ERROR: lazy loading failed for package 'RPANDA'
* removing 'C:/Users/XXX/R/win-library/3.5/RPANDA'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘RPANDA’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\XXX\AppData\Local\Temp\RtmpQhp14r\downloaded_packages’

**> library(devtools)**
**> install_github("hmorlon/PANDA")**
Downloading GitHub repo hmorlon/PANDA@master
from URL https://api.github.com/repos/hmorlon/PANDA/zipball/master
Installing RPANDA
"C:/PROGRA~1/R/R-35~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  "C:/Users/XXX/AppData/Local/Temp/RtmpQhp14r/devtools36507f816191/hmorlon-PANDA-05144d3"  \
  --library="C:/Users/XXX/Documents/R/win-library/3.5" --install-tests 

* installing *source* package 'RPANDA' ...
** R
** data
** inst
** tests
** byte-compile and prepare package for lazy loading
Error : object 'GIC' is not exported by 'namespace:mvMORPH'
ERROR: lazy loading failed for package 'RPANDA'
* removing 'C:/Users/XXX/R/win-library/3.5/RPANDA'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by JClavel** [comment]
Should work now with 'devtools'!
Regards,
Julien

**Comment by Cactusolo** [comment]
Thanks for the note!

I installed version 1.4 on my MAC, will try windows soon.

Miao
